-- Yearworm D1 schema. Apply with:
--   wrangler d1 execute yearworm --remote --file=schema.sql
CREATE TABLE IF NOT EXISTS scores (
  day     INTEGER NOT NULL,   -- daily number (#1 = 1 July 2026)
  device  TEXT    NOT NULL,   -- anonymous random token generated by the client
  nick    TEXT    NOT NULL,
  score   INTEGER NOT NULL,   -- 0..5
  time_ms INTEGER NOT NULL,   -- total thinking time (per-turn capped client-side)
  created INTEGER NOT NULL,   -- unix ms; breaks ties after score+time
  PRIMARY KEY (day, device)
);
CREATE INDEX IF NOT EXISTS idx_scores_day ON scores(day, score DESC, time_ms ASC);

-- challenge-set results: every finished run on a shared song set, keyed by the
-- set itself (pool indices joined with dots) — powers cross-device boards
CREATE TABLE IF NOT EXISTS chals (
  setkey  TEXT    NOT NULL,
  device  TEXT    NOT NULL,
  nick    TEXT    NOT NULL,
  score   INTEGER NOT NULL,
  time_ms INTEGER NOT NULL,
  created INTEGER NOT NULL,
  PRIMARY KEY (setkey, device)
);
CREATE INDEX IF NOT EXISTS idx_chals_set ON chals(setkey, score DESC, time_ms ASC);
